version: '3'

services:
  hapleyfrontend:
    image: hapleyfrontend
    build:
      context: frontend
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./frontend/src:/app/src # Links the source files to the running container
    ports:
      - 3000:3000
