name: Frontend CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: npm install --dev
    - name: Lint
      run: npm run lint && npm run format
    - name: Test
      run: npm test
