name: Lint and Test

on:
  pull_request:
    branches:
      - main

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install frontend dependencies
        run: cd frontend && npm ci
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'
    - name: Lint Frontend
      if: ${{ steps.changes.outputs.frontend == 'true' }}
      run: cd frontend && npm run lint && npm run format
    - name: Test Frontend
      if: ${{ steps.changes.outputs.frontend == 'true' }}
      run: cd frontend && npm test
